// Copyright (c) 2024 ONERA
// Authors: Susanne Claus
// This file is part of CutCells
//
// SPDX-License-Identifier:    MIT
#pragma once

// ---------------------------------------------------------------------------
// Thin lookup interface over Basix-generated quadrature tables.
// Generated headers live in cpp/src/generated/quadrature_tables_<cell>.h and
// are produced by tablegen/scripts/gen_quadrature_tables.py.
// ---------------------------------------------------------------------------

#include "cell_types.h"

#include "generated/quadrature_tables_interval.h"
#include "generated/quadrature_tables_triangle.h"
#include "generated/quadrature_tables_quadrilateral.h"
#include "generated/quadrature_tables_tetrahedron.h"
#include "generated/quadrature_tables_hexahedron.h"
#include "generated/quadrature_tables_prism.h"
#include "generated/quadrature_tables_pyramid.h"

#include <stdexcept>
#include <string>
#include <vector>
#include <concepts>

namespace cutcells::quadrature
{

/// Reference quadrature rule for given cell type and polynomial order.
/// Points are in the Basix canonical reference element.
/// Weights are the canonical integration weights (sum = reference cell volume).
///
/// The struct owns its data via std::vector<double>.  The template parameter T
/// is the requested floating-point precision; data is stored as double and
/// converted on construction.
template <std::floating_point T>
struct ReferenceQuadratureRule
{
    int _tdim       = 0;  ///< topological dimension of the canonical cell
    int _num_points = 0;  ///< number of quadrature points
    std::vector<T> _points;   ///< flat: _num_points * _tdim
    std::vector<T> _weights;  ///< flat: _num_points
};

// ---------------------------------------------------------------------------
// Internal helper – copy double arrays to vector<T>
// ---------------------------------------------------------------------------
namespace detail
{

template <std::floating_point T>
ReferenceQuadratureRule<T> make_rule(int tdim, int npts,
                                     const double* pts_d,
                                     const double* wts_d)
{
    ReferenceQuadratureRule<T> r;
    r._tdim       = tdim;
    r._num_points = npts;
    r._points.resize(static_cast<std::size_t>(npts) * tdim);
    r._weights.resize(static_cast<std::size_t>(npts));
    for (int i = 0; i < npts * tdim; ++i)
        r._points[i] = static_cast<T>(pts_d[i]);
    for (int i = 0; i < npts; ++i)
        r._weights[i] = static_cast<T>(wts_d[i]);
    return r;
}

} // namespace detail

// ---------------------------------------------------------------------------
// Public lookup function
// ---------------------------------------------------------------------------

/// Return the canonical quadrature rule for (cell_type, order).
/// Supports cell types: interval, triangle, quadrilateral, tetrahedron,
///                      hexahedron, prism, pyramid.
/// Supports orders 1..10 (as generated by gen_quadrature_tables.py).
/// Throws std::invalid_argument for unsupported combinations.
template <std::floating_point T>
ReferenceQuadratureRule<T> get_reference_rule(cell::type cell_type, int order)
{
    using namespace cutcells::quadrature::generated;

#define CUTCELLS_DISPATCH_CELL(CNAME, CTYPE)                                  \
    case cell::type::CTYPE:                                                   \
        switch (order) {                                                      \
            case  1: return detail::make_rule<T>(CNAME##_o1_tdim,  CNAME##_o1_npts,  CNAME##_o1_points,  CNAME##_o1_weights);  \
            case  2: return detail::make_rule<T>(CNAME##_o2_tdim,  CNAME##_o2_npts,  CNAME##_o2_points,  CNAME##_o2_weights);  \
            case  3: return detail::make_rule<T>(CNAME##_o3_tdim,  CNAME##_o3_npts,  CNAME##_o3_points,  CNAME##_o3_weights);  \
            case  4: return detail::make_rule<T>(CNAME##_o4_tdim,  CNAME##_o4_npts,  CNAME##_o4_points,  CNAME##_o4_weights);  \
            case  5: return detail::make_rule<T>(CNAME##_o5_tdim,  CNAME##_o5_npts,  CNAME##_o5_points,  CNAME##_o5_weights);  \
            case  6: return detail::make_rule<T>(CNAME##_o6_tdim,  CNAME##_o6_npts,  CNAME##_o6_points,  CNAME##_o6_weights);  \
            case  7: return detail::make_rule<T>(CNAME##_o7_tdim,  CNAME##_o7_npts,  CNAME##_o7_points,  CNAME##_o7_weights);  \
            case  8: return detail::make_rule<T>(CNAME##_o8_tdim,  CNAME##_o8_npts,  CNAME##_o8_points,  CNAME##_o8_weights);  \
            case  9: return detail::make_rule<T>(CNAME##_o9_tdim,  CNAME##_o9_npts,  CNAME##_o9_points,  CNAME##_o9_weights);  \
            case 10: return detail::make_rule<T>(CNAME##_o10_tdim, CNAME##_o10_npts, CNAME##_o10_points, CNAME##_o10_weights); \
            default: break;                                                   \
        }                                                                     \
        break

    switch (cell_type)
    {
        CUTCELLS_DISPATCH_CELL(interval,      interval);
        CUTCELLS_DISPATCH_CELL(triangle,      triangle);
        CUTCELLS_DISPATCH_CELL(quadrilateral, quadrilateral);
        CUTCELLS_DISPATCH_CELL(tetrahedron,   tetrahedron);
        CUTCELLS_DISPATCH_CELL(hexahedron,    hexahedron);
        CUTCELLS_DISPATCH_CELL(prism,         prism);
        CUTCELLS_DISPATCH_CELL(pyramid,       pyramid);
        default:
            throw std::invalid_argument(
                "get_reference_rule: unsupported cell type");
    }

#undef CUTCELLS_DISPATCH_CELL

    throw std::invalid_argument(
        "get_reference_rule: order " + std::to_string(order) +
        " not available (max order is 10; regenerate tables with higher max_order)");
}

} // namespace cutcells::quadrature
