#!/usr/bin/env python3
"""Offline Basix quadrature table generator for CutCells.

Usage:
    python gen_quadrature_tables.py [MAX_ORDER [OUTPUT_DIR]]

Defaults:
    MAX_ORDER  = 10
    OUTPUT_DIR = <repo_root>/cpp/src/generated

Environment variables (to override Basix lookup paths):
    BASIX_PYPATH  – path to basix Python sources  (e.g. .../basix/python)
    BASIX_SO_PATH – path to compiled _basixcpp.so  (e.g. .../basix/build/python)
"""

import sys
import os
import argparse

# ---------------------------------------------------------------------------
# Basix path bootstrap – use environment or well-known local build.
# ---------------------------------------------------------------------------
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DEFAULT_BASIX_PYTHON = os.path.join(os.path.dirname(_REPO_ROOT), "basix", "python")
_DEFAULT_BASIX_SO = os.path.join(
    os.path.dirname(_REPO_ROOT), "basix", "build", "python"
)

for _p in [
    os.environ.get("BASIX_SO_PATH", _DEFAULT_BASIX_SO),
    os.environ.get("BASIX_PYPATH", _DEFAULT_BASIX_PYTHON),
]:
    if _p and _p not in sys.path:
        sys.path.insert(0, _p)

import basix  # noqa: E402 (must come after path fixup)

# ---------------------------------------------------------------------------
# Cell-type table: (name, basix.CellType, topological_dimension)
# ---------------------------------------------------------------------------
CELL_TYPES = [
    ("interval", basix.CellType.interval, 1),
    ("triangle", basix.CellType.triangle, 2),
    ("quadrilateral", basix.CellType.quadrilateral, 2),
    ("tetrahedron", basix.CellType.tetrahedron, 3),
    ("hexahedron", basix.CellType.hexahedron, 3),
    ("prism", basix.CellType.prism, 3),
    ("pyramid", basix.CellType.pyramid, 3),
]

# ---------------------------------------------------------------------------
# Code-generation helpers
# ---------------------------------------------------------------------------

_HEADER_TMPL = """\
// AUTO-GENERATED by gen_quadrature_tables.py — do not edit.
// Basix {version} quadrature rules for '{cell_type}', orders 1..{max_order}.
// Regenerate: python tablegen/scripts/gen_quadrature_tables.py {max_order}
//
// SPDX-License-Identifier: MIT
#pragma once

#include <cstddef>

namespace cutcells::quadrature::generated
{{
"""

_FOOTER = "} // namespace cutcells::quadrature::generated\n"


def _fmt_doubles(arr, indent=4):
    """Format a flat numpy array as a C++ double initialiser list (no braces)."""
    vals = arr.ravel().tolist()
    pad = " " * indent
    cols = 4  # values per source line
    lines = []
    for i in range(0, len(vals), cols):
        chunk = vals[i : i + cols]
        lines.append(pad + ", ".join(f"{v:.18e}" for v in chunk))
    return ",\n".join(lines)


def _write_cell_header(cell_name, basix_ct, tdim, max_order, out_dir):
    fname = os.path.join(out_dir, f"quadrature_tables_{cell_name}.h")
    with open(fname, "w") as fh:
        fh.write(
            _HEADER_TMPL.format(
                version=basix.__version__,
                cell_type=cell_name,
                max_order=max_order,
            )
        )
        for order in range(1, max_order + 1):
            pts, wts = basix.make_quadrature(basix_ct, order)
            npts = pts.shape[0]
            pts_flat = pts.ravel()

            fh.write(f"// ---- order {order}: {npts} point(s), tdim={tdim} ----\n")
            fh.write(
                f"inline constexpr int    {cell_name}_o{order}_npts    = {npts};\n"
            )
            fh.write(
                f"inline constexpr int    {cell_name}_o{order}_tdim    = {tdim};\n"
            )
            fh.write(
                f"inline constexpr double {cell_name}_o{order}_points"
                f"[{npts * tdim}] = {{\n"
            )
            fh.write(_fmt_doubles(pts_flat))
            fh.write("\n};\n")
            fh.write(
                f"inline constexpr double {cell_name}_o{order}_weights[{npts}] = {{\n"
            )
            fh.write(_fmt_doubles(wts))
            fh.write("\n};\n\n")

        fh.write(_FOOTER)
    print(f"  {fname}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "max_order",
        nargs="?",
        type=int,
        default=10,
        help="Maximum quadrature order to generate (default: 10)",
    )
    parser.add_argument(
        "out_dir",
        nargs="?",
        default=os.path.join(_REPO_ROOT, "cpp", "src", "generated"),
        help="Output directory (default: cpp/src/generated)",
    )
    args = parser.parse_args()

    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    print(
        f"Generating Basix {basix.__version__} quadrature tables "
        f"(orders 1..{args.max_order}) -> {out_dir}"
    )
    for cell_name, basix_ct, tdim in CELL_TYPES:
        _write_cell_header(cell_name, basix_ct, tdim, args.max_order, out_dir)
    print("Done.")


if __name__ == "__main__":
    main()
