[build-system]
requires = ["scikit-build-core[pyproject]>=0.5.0", "nanobind>=2.0.0"]
build-backend = "scikit_build_core.build"

[project]
name = "cutcells"
version = "0.4.0"
description = "CutCells Python interface"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT AND BSD-3-Clause" }
authors = [
    { email = "susanne.claus@onera.fr" },
    { name = "Susanne Claus" },
]
dependencies = ["numpy>=1.21"]

[project.optional-dependencies]
docs = ["markdown"]
lint = ["ruff"]
optional = ["pyvista"]
test = ["pytest", "numpy"]
ci = ["mypy", "pytest-xdist", "cutcells[test]"]

[tool.scikit-build]
minimum-version = "0.5"
cmake.minimum-version = "3.21.0"
build-dir = "build/{wheel_tag}"
wheel.packages = ["cutcells"]
sdist.include = [
    "/LICENSE",
    "/README.md",
    "/third_party/THIRD_PARTY_NOTICES.md",
    "/third_party/VTK-Copyright.txt",
    "/third_party/Basix-LICENSE.txt",
    "/third_party/algoim/LICENSE",
    "/third_party/algoim/UPSTREAM_COMMIT",
    "/third_party/algoim/PATCHES.md",
]
sdist.exclude = [
    ".pytest_cache/",
]
wheel.license-files = [
    "LICENSE",
    "third_party/THIRD_PARTY_NOTICES.md",
    "third_party/VTK-Copyright.txt",
    "third_party/Basix-LICENSE.txt",
    "third_party/algoim/LICENSE",
    "third_party/algoim/UPSTREAM_COMMIT",
    "third_party/algoim/PATCHES.md",
]
