# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CutCells CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build using C++ and Python parts separately and run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install CutCells C++ library
      run: |
        cd cpp
        cmake -DCMAKE_BUILD_TYPE=Release -B build-dir -S . # Use make (not ninja)
        cmake --build build-dir
        sudo cmake --install build-dir
    - name: Install CutCells Python wrapper
      run: |
        cd python
        pip install .[test]
    - name: Test with pytest
      run: |
        cd python
        pytest tests/




          - name: Run units tests
            run: |
              pip install pytest-xdist # in ci extras, but most not needed.
              pytest -n auto --durations 20 test/
